# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160803_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datavalue',
            field=models.CharField(default='DATA', max_length=255, verbose_name='value'),
        ),
    ]
